media:
  input: src/assets
  output: /
content:
  - name: post
    label: Posts
    type: collection
    path: src/content/post
    view:
      fields: [ title, draft, date ]
    fields:
      - { name: author, label: Author, type: string }
      - { name: pubDatetime, label: Date, type: date }
      - { name: modDatetime, label: Date, type: date }
      - { name: title, label: Title, type: string, required: true }
      - { name: description, label: Description, type: string }
      - { name: metaTitle, label: Meta Title, type: string, required: true }
      - { name: metaDescription, label: Meta Description, type: string }
      - { name: ogImage, label: Title, type: string }
      - { name: slug, label: Slug, type: string }
      - { name: featured, label: Featured, type: boolean }
      - { name: draft, label: Draft, type: boolean }
      - { name: tags, label: Tags, type: string, list: true }
      - { name: body, label: Body, type: rich-text }
  - name: authors
    label: Authors
    path: src/content/author
    type: file
    view:
      fields: [ firstname, lastname, nickname, apdi, email ]
    fields:
      - { name: firstname, label: First Name, type: string }
      - { name: lastname, label: Last Name, type: string }
      - { name: nickname, label: Nick Name, type: string }
      - { name: apdi, label: apdi, type: string }
      - { name: email, label: Email, type: string }
      - { name: linkedin, label: Linkedin, type: string }
      - { name: twitter, label: Twitter, type: string }
      - { name: instagram, label: Instagram, type: string }
      - { name: facebook, label: Facebook, type: string }
  - name: about
    label: About page
    type: file
    path: src/pages/about.md
    fields:
      - { name: layout, type: string, hidden: true, default: layouts/base.njk }
      - { name: title, label: Title, type: string }
      - { name: body, label: Body, type: rich-text, options: { input: public/assets, output: /assets } }
